### ISSUE TITLE
Newsletter Guidelines

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#12]
### What's missing from the TRIP Guides

We need a simple overview of the basics of contributing issues of the TRIP Report newsletter.

### Expected content

Topics users might be interested in:

- The purpose of the newsletter
- Who can contribute to the newsletter
- What sort of contributions can be made to the newsletter
- How to contribute to the newsletter

### Actual content

Right now this is a stub page.

**Comment by Alejandro1954-ops** [comment]
100% agreed. 

And it does not need to be anything complicated. Attached is an example: 
![Nibiru Chain](https://github.com/TeleportXYZ/TRIP-Guides/assets/29745428/a454eb82-a748-48df-9509-fac786cb915a)

Added quarterly date estimates (Q2 2024) and add it as a separate category to the [guide](https://guides.trip.dev/).

**Comment by hwhelchel** [comment]
v1 shipped
