### ISSUE TITLE
TNC Licensing Best Practices

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#16]
### What's missing from the TRIP Guides

We need a simple overview of the basics of successfully applying for a TNC license.

### Expected content

Topics users might be interested in:

- How to apply for a TNC license
- How long it takes to get a TNC license
- What challenges crop up when applying for a TNC license
- Best practices for applying for a TNC license

### Actual content

This page does not exist yet.

**Comment by hwhelchel** [comment]
@Zippiwelch thanks! 

In terms of the workflow going forward, these github issues are akin to shortcut or asana tasks. It's to propose the work rather than include all the work. It's a bit confusing because I made the issue myself rather than have you do it. So no action needed here, just going forward when you create issues feel free to share some of the content of what you have in mind, but you don't need to have the full content ready to create an issue. Let me know if that doesn't make sense.

**Comment by r-woosley** [comment]
Would it be possible to add more information in regards to obtaining TNC insurance? Maybe some best practices or how it was done in Texas.

**Comment by Alejandro1954-ops** [comment]
> Would it be possible to add more information in regards to obtaining TNC insurance? Maybe some best practices or how it was done in Texas.

I support this. However, since each statement is different it may be best to keep it at a high level OR a hyperlink that leads to a seperate page with links for all 50 states (over time) and different nations.
