### ISSUE TITLE
Add sample ABM video in FAQ to showcase obtaining city threshold numbers 

### ISSUE THREAD

**Issue by tlow22** [TeleportXYZ/TRIP-Guides#19]
### What's missing from the TRIP Guides

I'd like to add a sample ABM video. There are currently two directions this could take:

1. Used to strengthen "how to unlock your city". Adding content to the `Explorer` section is probably a better segue into the ABM video as a "here's how we actually thought through these numbers". 

2. Showcase or explain in slightly more details how city threshold numbers are calculated. 

### Expected content

The content could be a continuation from the FAQ on the ABM Atomic Numbers or a yet-to-be-filled `Explorer` section and will elaborate the basis behind the city threshold numbers, namely balancing between: 

- Rider wait times 
- Driver utilization 

An ABM video will be used to highlight our capabilities towards capturing the city-to-city variation. 

There is demand for other videos for other cities, but since Guides is intended as a text-form, it might be best to use a single video to "show" and briefly tell why certain numbers are required for a city. 

### Actual content

An iframe of the video which on the company's [Google Drive](https://drive.google.com/file/d/1j5912IMgd9ak2eb71_-PHV2BC4VZgIIE/view?usp=drive_link) will be linked on the website. A potential improvement here is to link the keplergl app itself with a read-only without exposing the data, allowing users some form of zoom in/out interaction. There are some playback-sync issues that could be exposed, hence the fallback on videos. 

https://github.com/TeleportXYZ/TRIP-Guides/assets/32314421/f7490b54-4156-4ba3-8dd6-128b37597c77

**Comment by hwhelchel** [comment]
@tlow22 great initiative with this.

> Used to strengthen "how to unlock your city". Adding content to the Explorer section is probably a better segue into the ABM video as a "here's how we actually thought through these numbers".

The Explorer section should document the current state of the Explorer, not our future plans for it. The primary audience for the TRIP Guides is a web3/blockchain enthusiast who is new to TRIP and wants to learn more about how it works today.

Mixing in our plans for how it will work will cause unnecessary confusion and friction.

> Showcase or explain in slightly more details how city threshold numbers are calculated.

Showcasing how we reached the atomic network estimates makes a lot of sense.

> There is demand for other videos for other cities, but since Guides is intended as a text-form, it might be best to use a single video to "show" and briefly tell why certain numbers are required for a city.

We can start with one video, that said, if you have a video, or can get a video, for each of the cities in the Atomic Network Estimates page, I would spike on if there's a user friendly way to present them all alongside the data.

> An iframe of the video which on the company's [Google Drive](https://drive.google.com/file/d/1j5912IMgd9ak2eb71_-PHV2BC4VZgIIE/view?usp=drive_link) will be linked on the website. A potential improvement here is to link the keplergl app itself with a read-only without exposing the data, allowing users some form of zoom in/out interaction. There are some playback-sync issues that could be exposed, hence the fallback on videos.

Have you tested if GitBook supports iframes? We can also upload the videos to YouTube and embed them that way. I created a YouTube channel for Teleport this week.
