### ISSUE TITLE
Driver Basics

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#2]
### What's missing from the TRIP Guides

We need a simple overview of the basics of driving with TRIP.

### Expected content

Topics drivers might be interested in:

- How the take rate works
- How payouts work
- What driver safety measures are in place
- What's different about driving with TRIP versus traditional rideshare

### Actual content

Right now this is a stub page.

**Comment by hwhelchel** [comment]
@ivandiku here you go.

**Comment by hwhelchel** [comment]
Merged into issue here: https://github.com/TeleportXYZ/TRIP-Guides/issues/28

**Comment by ivandiku** [comment]
Hey Harry, I want to provide some clarity for drivers on the insurance coverage that Emory Peak maintains on their behalf. Let me know if you think this is appropriate. This is what I want to include:

Emory Peak Mobility provides the following insurance coverage for you:

**Offline Coverage**

When you're not driving for the service, your own personal auto insurance applies.

**Online and Waiting for a Trip**

- Up to $50,000 for individual bodily injuries and $100,000 per accident.
- Property damage coverage up to $25,000 per accident.

**During a Trip or Heading to Pick Up a Passenger**

- Third-party damages are covered up to $1,000,000 per incident.
- Your vehicle repair costs are covered up to its actual cash value of $50,000, with a deductible of $2,500, assuming your personal policy includes comprehensive and collision coverage.

**Comment by hwhelchel** [comment]
Looks good to me 👍
