### ISSUE TITLE
Naming: Balancers vs Guides vs Ambassadors?

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#21]

**Comment by hwhelchel** [comment]
Changing the name in GitBook back to Balancers to reflect the current state of the system for now.

Also "Guides" is now overloaded since the TRIP Guides site uses the word in a different context.

**Comment by r-woosley** [comment]
The Rideshare Protocol website states that there are 1,190 guides. Should this be 1,190 balancers?
