### ISSUE TITLE
How Balancers Work

### ISSUE THREAD

**Issue by avgur770** [TeleportXYZ/TRIP-Guides#33]
### What's missing from the TRIP Guides

balancer info.

### Expected content

~what is a balancer. specifically is it anyone that gives out referral codes or does someone need to sign up for it. 
~how are they rewarded? is it commission based or does it come from the team or token.
~and are there any other responsibility's 

### Actual content

not much

**Comment by Alejandro1954-ops** [comment]
Balancer issue is already open here[](https://github.com/TeleportXYZ/TRIP-Guides/issues/3)

**Comment by hwhelchel** [comment]
@avgur770 would love to have you flesh out how Balancers work on the "Balancer Basics" page in TRIP Guides.

Are you interested in doing that? If so, head over to the original issue here: #3 and let me know. 

Closing this issue as redundant to the original issue.
