### ISSUE TITLE
Cancelation Mechanics 

### ISSUE THREAD

**Issue by r-woosley** [TeleportXYZ/TRIP-Guides#35]
### What's missing from the TRIP Guides

A guide is needed to explain cancelations
 -How they are calculated
 -What excessive cancelations can lead to
 -Fees assessed
 
Having a fair, but robust cancelation policy is needed in order to operate a reliable service with on time pick ups. 

### Gist of expected content

Cancelation  
- What is a cancelation
- In app cancelation reasons
- How is the cancelation percentage calculated

Steps Taken 
- Proactive actions 
- Steps taken for high cancelation rates 
- When cancelations lead to deactivation 

Fees (On Demand/Scheduled)
-  State the fees that a driver or rider will pay for cancelation
-  The time parameters that result in these fees

### Gist of current content
No content present on this at the moment.

**Comment by hwhelchel** [comment]
Thank you for your contribution Ryan 👍 

In your experience, do cancelations typically behave differently or the same for drivers and riders? Is a cancelation percentage calculated for both drivers and riders? What is it used for? What do you mean by "Proactive actions"?

Ryan, when it comes to creating a guide here we want to follow the principle of "show don't tell". Meaning the guide content should always reflect the current state of the system instead of an ideal future state.

@abhilash710 what is our v1 cancelation mechanic for drivers and riders? My hunch is that Abhi will come back and share a simplified version of cancelation where some of these issues you raise are not yet addressed. That's totally ok.

In that scenario, we'd just want to document and map out how the current behavior works. That said, we can and should absolutely still discuss the points you raise here, especially if you feel strongly that some of them should be considered sooner rather than later and you can explain your reasoning as to why. Doesn't mean I or others will agree but we can at minimum have a constructive dialogue that 100% benefits the protocol and community.

**Comment by abhilash710** [comment]
Hey Ryan, the v1 of the cancellation logic is as follows:
- Riders can cancel the ride until just prior to being picked up
- The full fare is refunded back to the rider

We know that this favors the rider to start and will design the next version based on feedback from drivers.

Before drivers accept a ride, they will be able to see the full start and end destination of the ride. As well as how much they will earn for that ride. Driver have the ability to decline a ride without any consequences.

**Comment by r-woosley** [comment]
@hwhelchel 
> In your experience, do cancelations typically behave differently or the same for drivers and riders?
- On-demand rides: favor the driver as they have already accepted the request and are enroute to the pickup. The customer is given a time limit in which they have to cancel without being charged. Once that limit is reached the driver receives the full cancelation fee.  
- Scheduled Rides: 
         - Rider: Depending on when they cancel they pay a fee 
         - Driver: Have seen it where they have to pay a fee depending on when they cancel or lose access to schedules rides. 
        
>Is a cancelation percentage calculated for both drivers and riders? What is it used for? 
- I have only seen cancelation rates shown for drivers on the user side.  When this number exceeds a certain percent it can lead to deactivation.  
- I have seen rider cancelations tracked when looking at a drivers cancelations holistically. In some cases drivers will have the riders initiate cancelations so that it does not increase their on cancelation percentage. 

>What do you mean by "Proactive actions"?
-Proactive actions could be automated emails that are sent to the driver when their cancelation increases. This could highlight their cancelation rate and where they stand versus their market cancelation rate. Within the email add informational material tips from actual drivers on how to reduce the rate. 

- After the driver cancels have a screen that shows what their cancelation rate went to.

**Comment by r-woosley** [comment]
@abhilash710 
> Before drivers accept a ride, they will be able to see the full start and end destination of the ride. As well as how much they will earn for that ride. Driver have the ability to decline a ride without any consequences.

-Can you give any insight on what will happen if the ride goes longer/further or shorter than predicted? Will the fare be adjusted to the actual time and distance?

@hwhelchel 
One thing I failed to mention above is, it's imperative that the rider does not get charged a cancelation fee if the driver does not make forward progress to the pickup location. (Some drivers may be on another trip when they accepted or do not have the intention of completing the ride)

Here is an actual cancelation report from a rideshare company. As you can see if cancelations aren't monitored closely they can get out of hand. Drivers canceling hundreds more then they actually completed and then riders can not get a ride when they request. 
![Deactivation Report](https://github.com/TeleportXYZ/TRIP-Guides/assets/159962671/5c19f7e4-035c-4442-9ba9-5bb298670b4c)

**Comment by abhilash710** [comment]
> Can you give any insight on what will happen if the ride goes longer/further or shorter than predicted? Will the fare be adjusted to the actual time and distance?

At launch, the fare won't be adjusted based on the actual time and distance. We are calculating the fare based on route data (distance, time) we get from 3rd party APIs. We are going to be measuring the difference between the estimated (v) actual route and will adjust our fare calculation in the future.

**Comment by abhilash710** [comment]
@r-woosley -- Today, riders/drivers cannot cancel a trip after it has begun. A trip "begins" when the passenger has been picked up. Driver need to complete the trip (or swipe "complete" on the app) to end it. 

These are just the launch conditions, we have improvements on this lightly spec'd out but wanted to hear from real users before shipping the next version.

**Comment by hwhelchel** [comment]
@r-woosley great discussion here. Would you be open to synthesizing the learnings here in a contribution to TRIP Guides?

I could see there being a section in Rider Basics and Driver Basics on cancelation mechanics for each of them.

**Comment by r-woosley** [comment]
**Rider Cancellations**  
**Driver en route to a pickup-** Riders can cancel the ride at any time before the ride starts. The rider will not incur charges for the trip.
**After Pickup-** The rider can no longer cancel the trip once the driver has started the ride. The rider will be responsible for paying the full fare.
 
**Driver Cancelations**
**Driver en route to pickup-** While en route to the rider, the rider can cancel the ride for a full refund. 
**After Pickup-** The option to cancel the trip is no longer available. To end the ride, the driver will complete the ride in-app and will receive the total fare.

**Comment by hwhelchel** [comment]
@r-woosley awesome please feel free to create a change request with your proposed change in Gitbook and then request a review there and we'll get this shipped 👍

**Comment by r-woosley** [comment]
Change request submitted!

**Comment by r-woosley** [comment]
Change request submitted!

**Comment by r-woosley** [comment]
@abhilash710 I have one last question regarding cancelations. If a driver accepts a request and then cancels the request will the customer have to submit a new ride request or will the system auto-submit a new ride request?

**Comment by hwhelchel** [comment]
@r-woosley at this time, drivers cannot cancel rides once accepted.
