### ISSUE TITLE
Add Operator Requirements for Uruguay

### ISSUE THREAD

**Issue by GusMeg** [TeleportXYZ/TRIP-Guides#37]
### What's missing from the TRIP Guides

- Uruguay Operator Requirements

### Gist of expected content

Add requirements for establishing as an operator in Uruguay. Include contact info (with relevant government agencies) where possible.

### Gist of current content

Currently there's nothing about it on the Guide. This Issue was previously discussed with @hwhelchel, so I've already started working on getting the requirements and will post about it soon.

**Comment by hwhelchel** [comment]
This sounds great Gustavo. I think we should create some subpages under the Operator page.

For example:

```
Operator
  > South America
    > Uruguay
```

In the US, becoming an operator typically requires being a Transportation Network Company (TNC) or Transportation Network Provider (TNP) or Fleet Manager. So I'd try googling those terms as well searching for the Uruguay equivalents.

Also let's make sure to note that the requirements may change so users should check the official regulations (linked from the guide) for the most recent up to date requirements.

Share what you find here and then once you've done so I'll give you the thumbs up to go over into the Guides site and add this page.

**Comment by hwhelchel** [comment]
Let's make another issue here in GitHub to create stub pages for a bunch of popular countries for example more high income countries in South America, high income countries in Asia, Oceania, Europe, Africa, etc.

**Comment by GusMeg** [comment]
> Share what you find here and then once you've done so I'll give you the thumbs up to go over into the Guides site and add this page.

Sorry for the delay, but I was emailing back an forth with the government agency responsible for licensing Transport Operators here in Uruguay.

Here are the requirements:
*Disclaimer: Being a small country, most departments of Uruguay do not have a proper regulatory front for facing a service like Teleport. However, nowadays Uber and other rideshare companies operate in Uruguay with little to no requirements. The only exception is Montevideo (Uruguay's capital city) where there are "clear" regulations. Therefore I will list Montevideo's requirements for becoming a licensed transport operator*

- The operator must legally register as a company against social-security-agency ([BPS](https://www.bps.gub.uy/19382/banco-de-prevision-social.html)) and tax-agency ([DGI](https://servicios.dgi.gub.uy/serviciosenlinea)).
- The operator must have an *electronic address* for legal invoicing (registered email account).
- The operator must arrange a meeting with Montevideo's municipal Transport Department. The idea is to introduce them to Teleport and its workflow (*I assume this is only needed for the first few operators*). Here I leave a contact email of the [transport division](mailto: consultas.tpvp@imm.gub.uy) and a phone number +598 1950-9274.

**Comment by hwhelchel** [comment]
@GusMeg this is great. Please go ahead and create a change request in GitBook to contribute this to TRIP Guides.
