### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#47]
### What's missing from the TRIP Guides

We have a stub Contributors page that should list everyone who has published contributions to the TRIP Guides site.

For a v1 it can be simply a list of names. Over time it could evolve to include more information on the quantity and quality of contributions each contributor has made e.g. something like https://contributors.rubyonrails.org/

### Gist of expected content

List of names of everyone who has committed content to the TRIP Guides site.

### Gist of current content

No content is present.

**Comment by Alejandro1954-ops** [comment]
Full support. Only question is wen?

**Comment by Anton-Igudesman** [comment]
What is the status of this task? Does it need to be updated? Would love to tackle this as a first issue

**Comment by hwhelchel** [comment]
This has been completed. https://guides.trip.dev/contributors

@Anton-Igudesman would love your help with another task.
