### ISSUE TITLE
Newsletter Basics

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#5]
### What's missing from the TRIP Guides

We need a simple overview of the basics of the TRIP Report newsletter.

### Expected content

Topics users might be interested in:

- What's the purpose of the newsletter
- Who can write for the newsletter
- What sort of topics are good for the newsletter
- How often does the newsletter get published
- Where can I get the newsletter

### Actual content

Right now this is a stub page.

**Comment by Stretch379** [comment]
Is the newsletter gonna be directed towards everyone or is it gonna stay for internal and keep it between drivers and riders?

**Comment by hwhelchel** [comment]
@Stretch379 the content will be public and available to anyone interested in the TRIP protocol. That will include riders, drivers, balancers, operators, web3 enthusiasts, investors, and more.

**Comment by hwhelchel** [comment]
v1 written
