### ISSUE TITLE
Memes Idea 

### ISSUE THREAD

**Issue by Daniel257P** [TeleportXYZ/TRIP-Guides#50]
### Post Style

- [ ] Story
- [ ] Observation
- [ ] Contrarian
- [ ] Listicle
- [ ] Analyze
- [x] Other (share below)

### Post Template

- [ ] How can people do something, step-by-step?
- [ ] Inspire people to take action through a story or anecdote.
- [ ] Do a tear down of a company, person, content style, etc.
- [ ] Compare two situations for an interesting takeaway.
- [ ] How things work today vs. how you think in the future?
- [ ] What are you working on this week?
- [ ] Pain, Agitate, Intrigue, Positive Future, Solution
- [ ] A list of things (top books, people, podcasts, etc.)
- [ ] Something you feel differently about vs. the status quo.
- [ ] Book Quote
- [ ] Pencil Drawing
- [ ] Question
- [ ] What's something you've observed that you can talk about?
- [ ] How things worked in the past vs. how things work today.
- [ ] What went well and what went poorly. (Usually good for a Friday.)
- [x] Other (share below)

### Post Medium

- [ ] Video
- [x] Image
- [ ] Text
- [ ] Audio
- [ ] Other (share below)

### Post Location

- [ ] Teleport X Account
- [ ] Paul Bohm X Account
- [ ] Harry Whelchel X Account
- [x] Other (share below)

### Post Content

![1](https://github.com/TeleportXYZ/TRIP-Guides/assets/108595265/d98b6be0-b6de-4dfd-9b1a-51ce6b72de18)
![2](https://github.com/TeleportXYZ/TRIP-Guides/assets/108595265/08a67be3-e8e3-4894-aa52-f70e43a68027)
![Chart (1)](https://github.com/TeleportXYZ/TRIP-Guides/assets/108595265/8b34e7f2-bbdd-4878-bd7a-001d47169022)
![Blue Light Green Modern Finance Pie Chart Strategy Instagram Post](https://github.com/TeleportXYZ/TRIP-Guides/assets/108595265/e0aeef05-6033-49e2-ba77-a40f1c977bb0)

**Comment by Daniel257P** [comment]
> Daniel love these! Have you tried any of them in the wild yet? What has been the response?

> I haven't shared them yet; I'm just making examples. I'm inviting some friends who are good at making memes to collaborate here. I'll use them to see the audience's reaction.

> Can you make versions without the supermeme.ai text in the bottom right hand corner?

Yes, I can remove the watermark

**Comment by hwhelchel** [comment]
Awesome I'd remove the watermark and then have you and your buddies share them on social media. Let us know which ones resonate more than others. Take screenshots of the engagement they get and then we can take the best ones and include them in the TRIP Guides site 🔥

**Comment by hwhelchel** [comment]
You can also spread them to folks in the TRIP Community on Telegram and encourage them to post them on social media and report back on the engagement they get.

**Comment by Alejandro1954-ops** [comment]
@hwhelchel this would be perfect to push on a platform like Galxe, Zealy, or TaskOn. 

I think Teleport is already on one of these platforms? Meme creators can be compensated with XP rather than any monetary payout. 

What do you think @Daniel257P ? Perhaps we can just let this thread run with meme creations.

**Comment by Daniel257P** [comment]
> @hwhelchel this would be perfect to push on a platform like Galxe, Zealy, or TaskOn.
> 
> I think Teleport is already on one of these platforms? Meme creators can be compensated with XP rather than any monetary payout.
> 
> What do you think @Daniel257P ? Perhaps we can just let this issue run with meme creations.

I agree that we involve meme creators and encourage them in that way.

**Comment by Alejandro1954-ops** [comment]
@Daniel257P to be clear, which way?

Keeping meme creation here on the issue thread or through a bounty/task platform i.e. Zealy, Galxe, etc. ?

**Comment by hwhelchel** [comment]
At the moment we want to focus on our native TRIP Rewards as an incentive mechanism to influence user behavior.

It might make sense to explore one of these platforms in the future.

Closing this issue for now as we don't have any memes in this thread that are proven in the wild as effective to add to the Guides site.
