### ISSUE TITLE
Dominican Republic Operator Requirement 

### ISSUE THREAD

**Issue by Daniel257P** [TeleportXYZ/TRIP-Guides#52]
### What's missing from the TRIP Guides

- Dominican Republic Operator Requirements

### Gist of expected content

- Include Contact info and links to resources for operator applicants.
- Detailed step-by-step process for registering as a TNC, TNP, or Fleet Manager.
- Overview of licensing requirements.
- Guidance on obtaining required insurance.
- Indicators needs in the formula to determine the Atomic Network Estimates for areas in the Dominican Republic

### Gist of current content

- Basic information on registering as a TNC, TNP, or Fleet Manager.

- To become a operator you must meet local licensing and insurance requirements.

**Comment by Daniel257P** [comment]
To operate a ridesharing company in the Dominican Republic, a license issued by INTRANT (National Institute of Transit and Land Transport) is required. Here is the link with the requirements for this license. [Here](https://intrant.gob.do/index.php/servicios/servicios-licencia-de-operacion-transporte-privado/item/874-licencia-de-operacion-companias-taxis-por-comunicacion)

**Comment by Willmolina19** [comment]
Adding to current needed contentfor the rider:

Personal ID, license, vehicle documentation is require for riders.

**Comment by Alejandro1954-ops** [comment]
@Daniel257P @Willmolina19 please check [this comment](https://github.com/TeleportXYZ/TRIP-Guides/issues/37#issuecomment-1946507191) under the issue. :)

**Comment by hwhelchel** [comment]
@Daniel257P would be great to have you add this as a change request in gitbook for the guides site.

Please make sure to observe the information architecture proposed in this comment: https://github.com/TeleportXYZ/TRIP-Guides/issues/37#issuecomment-1946507191

**Comment by Daniel257P** [comment]
Here are the requirements:
Disclaimer: Before taking any action, it is strongly recommended to consult with legal and business professionals familiar with the laws and regulations of the Dominican Republic. Laws and regulations are subject to change, and the steps provided may not be exhaustive or up to date at the time of your reading.

- Register the company with the [Chamber of Commerce] (https://www.camarasantodomingo.do/), specifying the commercial activities the company will be engaged in.
- Complete the company's registration with the [RNC] (https://dgii.gov.do/Paginas/default.aspx)to obtain a taxpayer identification number.
- Obtain the necessary commercial license from the DGII to legally operate the ridesharing service.
- Complete the company's registration with the [Ministry of Labor] (https://mt.gob.do/) to ensure compliance with labor regulations.
- Open a business bank account to manage financial transactions related to the ridesharing operations.
- Once registered and prepared, apply for the Operating License for [Taxi Communication Companies] (https://intrant.gob.do/index.php/servicios/servicios-licencia-de-operacion-transporte-privado/item/874-licencia-de-operacion-companias-taxis-por-comunicacion) from INTRANT, which oversees transportation and traffic matters.

**Comment by Daniel257P** [comment]
> add this as a change request in gitbook for the guides site.

How can I add this as a change request in GitBook? I would like to know if this is how I should present the proposal according to the mentioned architecture.

**Comment by hwhelchel** [comment]
Click the link in this section on how to create a gitbook account then skim this doc 

https://guides.trip.dev/contributing/contributing-to-trip#commenting-on-change-requests
https://docs.gitbook.com/content-editor/editor/change-requests

**Comment by Daniel257P** [comment]
I'm not sure if I followed the correct steps to review this change request. [Here's the link for you to check](https://app.gitbook.com/invite/wzi1KTJobrPOLSxTnxC4/BRKrvsUrcers1Bz28tDF). If anything is missing or needs correction, please let me know so I can improve and understand how to do better with any future proposals. Sorry, this is my first time contributing here on GitHub and Gifbook.

**Comment by hwhelchel** [comment]
@Daniel257P that is a link to join your personal gitbook account. You need to join our gitbook workspace and create the change request there.

**Comment by Daniel257P** [comment]
> @Daniel257P that is a link to join your personal gitbook account. You need to join our gitbook workspace and create the change request there. No apologies necessary.

Ok, I think I got it, I finally made the change request ha

**Comment by hwhelchel** [comment]
Yes, your change request set up is great. Looping in some team members there to help review your work. Looking good 👍

**Comment by hwhelchel** [comment]
@Daniel257P please close this issue now that your work has been merged, thank you.
