### ISSUE TITLE
Adding more signup data to the TRIP Guides / (TRIP Explorer) 

### ISSUE THREAD

**Issue by tlow22** [TeleportXYZ/TRIP-Guides#58]
### What's missing from the TRIP Guides

Would like to get some ideation and discussion started towards an initial dashboard or data display on the TRIP Guides.

The [TRIP Explorer](https://explorer.trip.dev/) currently gives an idea of signup growth geographically. Some ideas here: 
- A regional signup leaderboard (city and/or by country) 
   - An initial attempt could just have the top 10, but ideally something with a search bar to allow users to search for their own city is ideal 
- Time series plot of signups

Similarly, we collect driver interest forms. It may be a good idea to show growth in driver interest in addition to regular signups. 

Intentionally keeping first post short but very open to other ideas!

### Gist of expected content
The first step is to have this on TRIP Guides via an embed. At this point, it seems the content would be well placed in the Explorer Basics section (#4) or a sub-section in there.

**Comment by Stretch379** [comment]
It would be nice if there was and active counter for each city to see how far we are from expanding to that city

**Comment by r-woosley** [comment]
Would like to see a live number of signups (rider/driver) vs what's needed to unlock a city. Also, dense metros will be unlocked, but show how the service area can expand into the suburbs. 

Once a city is unlocked a continuous forecast of how many riders are needs to keep marketplace efficiency. What is needed gets rewarded more than the other.

**Comment by tlow22** [comment]
@Stretch379, @r-woosley glad to see you guys on here!
Yep, going to put some time towards getting info on this. More specifically, a progress indicator towards unlocking cities. 

The idea on continuous forecast after a market is unlocked is a really interesting one, will keep this suggestion in mind.

**Comment by hwhelchel** [comment]
@tlow22 thanks for this contribution. Let's merge this into the original Explorer Basics page. Agreed this content can live there. Please also flesh out the Explorer Basics page while you're at it. If you're unclear on how to do that, ask questions in #4 here.

Please feel free to move forward on all this and make a Change Request if you haven't.

Merged into: #4
