### ISSUE TITLE
Getting started guide in your area.

### ISSUE THREAD

**Issue by K-Swans** [TeleportXYZ/TRIP-Guides#59]
1. User-Friendly Interface: For both riders and drivers using the Teleport Rideshare app. Riders should be able to effortlessly request a ride, and drivers should find it straightforward to accept these requests.
2. Cancellation Policy (Other ride/share applications): If a driver cancels, it’s a strike against them. However, ending a cancellation early is usually free within a certain time window. Otherwise, it’s a small fee (around $2-$4).
3. Promote the App: When interacting with potential customers, take the opportunity to tell them about the app and its benefits.
4. Surge Pricing Strategy: During surge pricing, the cancellation fee can be significant. As a driver, you can cancel and refund the rider in the app, explaining it was an accident. As long as this doesn’t happen too frequently (e.g., once every 3-4 rides), it won’t trigger a flag from the rideshare company.
5. Track and Target Surges: Keep your phone in a mode that allows tracking of surge areas. Go to these areas of heavy congestion, but don’t use the app to pick up riders. Instead, make an offer to potential riders in person. Even with surges, they would be paying a reduced price compared to the base price. 
6. Remember, the goal is to provide a reliable, cost-effective service that benefits both riders and drivers. This strategy could lead to an influx of new users for Teleport.

**Comment by hwhelchel** [comment]
@K-Swans thank you for your contribution!

I don't understand what guide you are proposing. Please use the issue template provided to structure your submission.

Many of the points you reference don't exist in the system at this time. The Guides site is to explain how things work today, not how it should work or will work in the future.

Here are some existing issues that overlap with yours

Requesting a ride: https://github.com/TeleportXYZ/TRIP-Guides/issues/62
Completing a trip: https://github.com/TeleportXYZ/TRIP-Guides/issues/61
More on cancellation: https://github.com/TeleportXYZ/TRIP-Guides/issues/35
Promoting the app: Search the issue tracker there are a few

Surge pricing doesn't exist at this time.
