### ISSUE TITLE
Operators

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#6]
### What's missing from the TRIP Guides

We need a simple overview of the basics of Operating with TRIP.

### Expected content

Topics operators might be interested in:

- How operating works
- How operators make money
- How to become an operator
- What's different about operating with TRIP versus traditional rideshare

### Actual content

Right now this is a stub page.

**Comment by danie-beukman** [comment]
### **What is an Operator?**

An Operator handles the regulatory and operational requirements of providing rideshare service.

<img width="742" alt="Screenshot 2023-11-06 at 4 13 03 PM" src="https://github.com/TeleportXYZ/TRIP-Guides/assets/159361266/b3fa8637-ac99-4302-89ef-fbbf96789ab4">

### **What are the requirements of an Operator?**

All Operators must be validated on the network by a Compliance Auditor. At a minimum, all Operators:

- Must establish mechanisms for registering and responding to customer requests and complaints.
- Have credible and qualified owners and leadership.
- Must have a valid rideshare license and rideshare insurance.

### **What responsibilities does an Operator have?**

Operators must obtain licenses and insurance, and be operationally prepared to comply with regulatory and safety requirements in each geography they wish to serve, before they can begin matching riders and drivers within those locations. 

Operators who operate using the TRIP Protocol are subject to the same requirements as rideshare operators who operate outside the TRIP Protocol. This includes: 

- Full compliance with all applicable local regulations and laws.
- Handling customer support requests.
- Cooperating with law enforcement.
- Resolving disputes and issuing refunds.

### **What is the benefit of becoming an Operator?**

<img width="750" alt="Screenshot 2023-11-06 at 4 28 36 PM" src="https://github.com/TeleportXYZ/TRIP-Guides/assets/159361266/5fc0b569-a130-4696-99cc-cc64524a6dbe">

Operators connect drivers and riders and get compensated with a percentage of fares, as well as network rewards issued by the protocol.

Running an operator is running a business that enables the rideshare network to operate.

### How does operating an Operator work?

After Operators have acquired licensing and insurance, they run a piece of software called a “rideshare server” that helps them connect drivers & riders as well as handle customer support requests. Most of the work involved is fairly automated and straightforward. DEC (Teleport’s parent company) also operates a Software-as-a-Service system that helps independent operators run the software in the cloud in an automated fashion.

### Can there be more than one operator in an area?

Yes. The reason prices on TRIP always stay fairer is that multiple Operators can compete on pricing.

### How do I get started?

It’s early. No city has launched on TRIP yet. But over time the process will require you to get a license from your state, country, or municipality, and get all the required insurance. A compliance auditor will then validate that your business is capable of and permitted to operate. Next, you [reach out to us](https://44kus966t0o.typeform.com/to/YFyZeLuy), and someone from our team can help you set up the rideshare server so your company can get ready to operate.

**Comment by hwhelchel** [comment]
@danie-beukman this is awesome, good stuff. Ready to be added to GitBook in a change request.

No action needed here, but in the future, think of these github issues as akin to shortcut or asana tasks. The issue is to propose the change, organize a discussion around it, get alignment before starting the writing or content gathering process. 

So if you ever have a proposal for a guide, newsletter issue, any content that's public facing, etc. you can create the issue right away before any writing has been done or content has been gathered.

**Comment by hwhelchel** [comment]
The general points of feedback I left here https://github.com/TeleportXYZ/TRIP-Guides/issues/7 today apply here as well 👌
