### ISSUE TITLE
Litepaper Images

### ISSUE THREAD

**Issue by hwhelchel** [TeleportXYZ/TRIP-Guides#64]
### What's missing from the TRIP Guides

We recently updated the litepaper. These updates included simplifying the naming of different concepts on the TRIP protocol.

The images throughout the litepaper need updating to reflect the new naming conventions.

### Gist of expected content

Compliance Auditors should be renamed to Auditors in the images.
Client Apps should be renamed to Apps in the images.

etc...

### Gist of current content

Currently the images use the old names for TRIP protocol concepts.

**Comment by hwhelchel** [comment]
Images here on this page as well need updating https://guides.trip.dev/other-roles/operators

**Comment by matt-brigante** [comment]
<img width="1919" alt="Authorization" src="https://github.com/TeleportXYZ/TRIP-Guides/assets/159580669/bb718b69-c24d-4c4f-a15d-2bf7bebd8ab9">
<img width="1919" alt="Dispute Resolution" src="https://github.com/TeleportXYZ/TRIP-Guides/assets/159580669/8788ba63-2dfa-4bfa-954a-b93088414f78">
<img width="1917" alt="Key-Centric Identity" src="https://github.com/TeleportXYZ/TRIP-Guides/assets/159580669/27a6688d-3e46-4f53-baf4-b5c61b0dcd3b">
<img width="1919" alt="Payment" src="https://github.com/TeleportXYZ/TRIP-Guides/assets/159580669/72df865a-78a3-4459-9513-0b2d3af875a8">
<img width="1919" alt="Token Issuance" src="https://github.com/TeleportXYZ/TRIP-Guides/assets/159580669/7c954245-6c77-4227-a764-dc43308c7d84">

**Comment by matt-brigante** [comment]
Above are the updates images - please review

**Comment by hwhelchel** [comment]
@matt-brigante looks great. One tweak I'd make is changing "Local Regulators" to "Regulators"
