### ISSUE TITLE
Trip Bot 

### ISSUE THREAD

**Issue by r-woosley** [TeleportXYZ/TRIP-Guides#65]
### What's missing from the TRIP Guides

Show trip community members how Trip Bot and the knowledge base were developed/deployed. 

### Gist of current content

No content is currently available at this time.

**Comment by hwhelchel** [comment]
@r-woosley the bot is no longer being used therefore any content about it would not be describing the current state of TRIP or the broader TRIP ecosystem.

What's more, we need to make sure all the contributions either directly or indirectly help advance us towards our current goals: https://guides.trip.dev/#trip-goals

I don't think it makes sense to add this right now.
